[settings]
module = django
python_files = tests.py test_*.py *_tests.py
env_list =
    DJANGO_SETTINGS_MODULE=lender.test_settings
    DATABASE_URL=postgresql://lender_user:lender_password@db:5432/lender_test_db
