# Generated by Django 6.1.1 on 2026-09-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('PUSH', 'Push (sent to DAIRE)'), ('PULL', 'Pull (received from DAIRE)')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('borrower_references', models.JSONField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daire_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Exchange Log',
                'verbose_name_plural': 'Data Exchange Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
