# Generated by Django 6.1.1 on 2026-09-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='borrower',
            field=models.OneToOneField(blank=True, help_text='Linked borrower record (for self-service portal users only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user', to='core.borrower'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DATA_OFFICER', 'Data Officer'), ('AUDITOR', 'Auditor'), ('READ_ONLY', 'Read-only User'), ('CENTRAL_SYSTEM', 'DAIRE Central System'), ('BORROWER', 'Borrower (Self-Service Portal)')], default='READ_ONLY', max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DATA_OFFICER', 'Data Officer'), ('AUDITOR', 'Auditor'), ('READ_ONLY', 'Read-only User'), ('CENTRAL_SYSTEM', 'DAIRE Central System'), ('BORROWER', 'Borrower (Self-Service Portal)')], max_length=30),
        ),
    ]
